before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - "forge.babariviere.com/babariviere/ntfy-bridge:{{ .Tag }}"
      - "forge.babariviere.com/babariviere/ntfy-bridge:{{ .Major }}"
      - "forge.babariviere.com/babariviere/ntfy-bridge:{{ .Major }}.{{ .Minor }}"
      - "forge.babariviere.com/babariviere/ntfy-bridge:latest"
    dockerfile: release/Dockerfile

docker_manifests:
  - name_template: "forge.babariviere.com/babariviere/ntfy-bridge:{{ .Tag }}"
  - name_template: "forge.babariviere.com/babariviere/ntfy-bridge:{{ .Major }}"
  - name_template: "forge.babariviere.com/babariviere/ntfy-bridge:{{ .Major }}.{{ .Minor }}"
  - name_template: "forge.babariviere.com/babariviere/ntfy-bridge:latest"

gitea_urls:
  api: https://forge.babariviere.com/api/v1
  download: https://forge.babariviere.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
